### ISSUE TITLE
Invalid package name

### ISSUE THREAD

**Issue by a-bashtannik** [shutterstock/php-shutterstock-api#1] opened 2016-06-06 14:39 UTC
Hi

Your repository is `shutterstock/php-shutterstock-api` but package name is 'shutterstock/api'.

`composer require shutterstock/php-shutterstock-api` will fail.

You have to rename repository and readme.md or package name.

Now `composer require shutterstock/api` works fine.

**Comment by meishern** [comment] 2017-02-23 11:44
Thank you. Worked for me.

**Comment by belguinan** [comment] 2018-05-04 13:05
Thank you

**Comment by behradkhodayar** [comment] 2018-09-25 07:14
The issue is reported 2 years ago & still existing?!! What do you do there at ShutterStock?!

**Comment by jacobemerick** [comment] 2018-09-28 13:59
Closed in #2

**Closed as completed by jacobemerick** 2018-09-28 13:59 UTC
